# Generated by Django 5.2.15 on 2026-09-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_businessmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmembership',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='businessmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('viewer', 'Viewer'), ('inventory', 'Inventory'), ('accountant', 'Accountant'), ('reports', 'Reports'), ('warehouse', 'Warehouse'), ('custom', 'Custom')], default='cashier', max_length=20),
        ),
    ]
