# Generated by Django 5.2.15 on 2026-09-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_businessmembership_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=20),
        ),
    ]
