# Generated by Django 5.2.15 on 2026-08-31 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0005_restore_tiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('locked', 'Locked'), ('disabled', 'Disabled'), ('removed', 'Removed')], db_index=True, default='active', max_length=20)),
                ('role_key', models.CharField(blank=True, default='owner', max_length=50)),
                ('secret_hash', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_devices', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_devices', to='licenses.license')),
            ],
            options={
                'verbose_name': 'Sync Device',
                'verbose_name_plural': 'Sync Devices',
                'unique_together': {('business', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_seq', models.BigIntegerField(default=0)),
                ('entity', models.CharField(max_length=80)),
                ('entity_uuid', models.CharField(db_index=True, max_length=64)),
                ('op', models.CharField(max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='sync.syncdevice')),
            ],
            options={
                'verbose_name': 'Sync Record',
                'verbose_name_plural': 'Sync Records',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['business', 'id'], name='sync_syncre_busines_f6a520_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'device', 'client_seq'), name='uniq_sync_business_device_seq')],
            },
        ),
    ]
