# Generated by Django 5.2.15 on 2026-09-04 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginattempt'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainCommit',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='audit_chain_commit', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('head_hash', models.CharField(max_length=64)),
                ('records', models.JSONField(default=list)),
                ('committed_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_chain_commits', to='sync.syncdevice')),
            ],
            options={
                'verbose_name': 'Audit Chain Commit',
                'verbose_name_plural': 'Audit Chain Commits',
            },
        ),
    ]
