# Generated by Django 5.2.15 on 2026-09-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_pairinginvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairinginvitation',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_invitations', to='sync.syncdevice'),
        ),
        migrations.AlterField(
            model_name='pairinginvitation',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
