# Generated by Django 5.2.15 on 2026-09-07 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_syncdevice_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdevice',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The person (account) this device belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syncdevice',
            name='business',
            field=models.ForeignKey(help_text='The tenant business (owner User with is_customer=True).', on_delete=django.db.models.deletion.CASCADE, related_name='sync_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
