# Generated by Django 5.2.15 on 2026-09-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_syncdevice_user_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairinginvitation',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='pairinginvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
