# Generated by Django 6.0.4 on 2026-06-08 09:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('device_limit', models.IntegerField(default=1, help_text='0 means unlimited')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License Plan',
                'verbose_name_plural': 'License Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('device_limit', models.IntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('is_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licenses.licenseplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_index=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='licenses.license')),
            ],
            options={
                'verbose_name': 'License Audit Log',
                'verbose_name_plural': 'License Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('operating_system', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_activations', to='licenses.license')),
            ],
            options={
                'ordering': ['-activation_date'],
                'unique_together': {('license', 'device_id')},
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_key', 'status'], name='licenses_li_license_3f2f22_idx'),
        ),
    ]
