# Generated by Django 5.2.15 on 2026-09-07 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MorVerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin_digest', models.CharField(db_index=True, max_length=64)),
                ('tin_masked', models.CharField(max_length=16)),
                ('sub_tin_masked', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('not_found', 'Not found'), ('unavailable', 'Unavailable'), ('failed', 'Failed')], max_length=20)),
                ('source', models.CharField(choices=[('mor', 'Ministry of Revenues (live)'), ('backend', 'Shega backend cache')], default='mor', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mor_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tin_digest', 'created_at'], name='mor_morveri_tin_dig_f99e10_idx')],
            },
        ),
    ]
